#!/usr/bin/env python

# whaledo [-h|--help|--version]
# whaledo alias SHORTNAME=LONGNAME # Alias SHORTNAME to the Docker Hub image LONGNAME.
# whaledo unalias SHORTNAME        # Unalias SHORTNAME.
# whaledo LONGNAME COMMAND         # Run command in the Docker image referenced by LONGNAME
# whaledo SHORTNAME COMMAND        # Run COMMAND in the Docker image referenced by the LONGNAME that SHORTNAME is aliased to.
#
# TODO: Figure out how to handle volumes and such.
# NOTE: I am going to be making a repo of Dockerfiles specifically for this, so I am okay using some kind of convention for mounting things instead of making it infinitely tweakable.
#       E.g., always mounting . to /tmp/work or $HOME to /tmp/home or something like that, or doing `whaledo [SHORTNAME|LONGNAME] COMMAND [MOUNTPOINTS...]` and just doing a 1:1 mapping.
#       An alternative approach could be to get metadata files from the whaledo-containers GitHub repo that explain what should be mounted where, but use the containers from Docker Hub just to make it quicker/less annoying.
#
# Example usage:
# $ whaledo alias rgdev=duckinator/rubygems-development
# $ whaledo rgdev rake test # Run `rake test` in a Docker container using the duckinator/rubygems-development image.
# $ whaledo unalias rgdev

import os
import json
import click

aliases = {}

# ASSUMPTION: Will never be given a file with nothing but a newline in it.
def load_aliases(filename):
    ret = None
    if os.path.isfile(filename) and os.stat(filename).st_size != 0:
        with open(filename, 'r') as f:
            ret = json.load(f)

    if ret == None:
        ret = {}

    return ret

def save_aliases(filename):
    with open(filename, 'w') as f:
        json.dump(aliases, f)

@click.group()
def cli():
    pass

@cli.command()
@click.argument("short_name")
@click.argument("long_name")
def alias(short_name, long_name):
    aliases[short_name] = long_name

@cli.command()
@click.argument("short_name")
def unalias(short_name):
    return aliases.pop(short_name, None)

# FIXME: This function is pure sadness.
@cli.command()
def aliases():
    separator_length = max(map(len, aliases)) + 8 # Arbitrary offset (8).
    separator_length = min(separator_length, 20)  # Arbitrary length.
    print(("ALIAS{:<" + str(separator_length) + "}REPOSITORY").format(' '))
    for short_name in aliases:
        print(("{}{:<" + str(separator_length) + "}{}").format(short_name, ' ', aliases[short_name]))

cli.add_command(alias)
cli.add_command(unalias)
cli.add_command(aliases)

if __name__ == '__main__':
    alias_filename = os.path.join(os.environ['HOME'], '.whaledo_aliases.json')
    aliases = load_aliases(alias_filename)

    try:
        cli()
    finally:
        save_aliases(alias_filename)
